import { Platform, StatusBar as RNStatusBar, Dimensions, StyleSheet } from 'react-native';

export const ANDROID_TOP = Platform.OS === 'android' ? (RNStatusBar.currentHeight || 24) : 0;
export const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  loginScreen: { flex: 1, backgroundColor: '#f1f5f9', justifyContent: 'center', paddingHorizontal: 24 },
  loginCard: { backgroundColor: '#ffffff', borderRadius: 24, padding: 28, shadowColor: '#000', shadowOpacity: 0.07, shadowRadius: 20, elevation: 5 },
  brandText: { fontSize: 15, fontWeight: '800', color: '#2563eb', letterSpacing: 0.5, marginBottom: 20 },
  cardTitle: { fontSize: 26, fontWeight: '800', color: '#0f172a', marginBottom: 6 },
  cardSubtitle: { fontSize: 14, color: '#64748b', marginBottom: 28 },
  label: { fontSize: 13, fontWeight: '600', color: '#475569', marginBottom: 8 },
  input: { height: 50, backgroundColor: '#f8fafc', borderRadius: 12, paddingHorizontal: 16, marginBottom: 16, color: '#0f172a', fontSize: 15, borderWidth: 1, borderColor: '#e2e8f0' },
  error: { color: '#dc2626', fontSize: 13, marginBottom: 10 },
  hintBox: { marginTop: 14, backgroundColor: '#eff6ff', padding: 12, borderRadius: 12, alignItems: 'center' },
  hintText: { color: '#1d4ed8', fontSize: 12, fontWeight: '500' },
  primaryButton: { backgroundColor: '#2563eb', borderRadius: 14, paddingVertical: 15, alignItems: 'center', marginTop: 6, shadowColor: '#2563eb', shadowOpacity: 0.3, shadowRadius: 12, elevation: 5 },
  primaryButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  secondaryButton: { backgroundColor: '#f1f5f9', borderRadius: 14, paddingVertical: 14, alignItems: 'center', marginTop: 10, borderWidth: 1, borderColor: '#e2e8f0' },
  secondaryButtonText: { color: '#374151', fontSize: 15, fontWeight: '600' },
  screenWrapper: { flex: 1, backgroundColor: '#f8fafc', paddingTop: ANDROID_TOP },
  screenContent: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 32 },
  dashHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  dashGreeting: { fontSize: 13, color: '#94a3b8', fontWeight: '500', marginBottom: 2 },
  dashName: { fontSize: 24, fontWeight: '800', color: '#0f172a' },
  avatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#2563eb', justifyContent: 'center', alignItems: 'center', shadowColor: '#2563eb', shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  avatarText: { color: '#fff', fontSize: 18, fontWeight: '800' },
  scanCard: { backgroundColor: '#1e3a8a', borderRadius: 20, padding: 18, flexDirection: 'row', alignItems: 'center', marginBottom: 16, shadowColor: '#1e3a8a', shadowOpacity: 0.35, shadowRadius: 16, elevation: 6 },
  scanCardIconBox: { width: 56, height: 40, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.12)', justifyContent: 'center', alignItems: 'center', marginRight: 14, paddingHorizontal: 6 },
  scanCardTitle: { color: '#ffffff', fontSize: 15, fontWeight: '700', marginBottom: 3 },
  scanCardSubtitle: { color: 'rgba(255,255,255,0.6)', fontSize: 12 },
  scanCardArrow: { color: 'rgba(255,255,255,0.4)', fontSize: 30, marginLeft: 8, lineHeight: 34 },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  statBox: { flex: 1, backgroundColor: '#ffffff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#e2e8f0', shadowColor: '#000', shadowOpacity: 0.03, shadowRadius: 6, elevation: 1 },
  statNumber: { fontSize: 22, fontWeight: '800', color: '#0f172a', marginBottom: 4 },
  statLabel: { fontSize: 12, color: '#94a3b8', fontWeight: '500' },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#0f172a', marginBottom: 14 },
  emptyState: { alignItems: 'center', paddingTop: 40 },
  emptyIcon: { fontSize: 42, marginBottom: 12 },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: '#374151', marginBottom: 6 },
  emptySubtitle: { fontSize: 13, color: '#9ca3af' },
  historyItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 14, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: '#f1f5f9', shadowColor: '#000', shadowOpacity: 0.03, shadowRadius: 6, elevation: 1 },
  historyDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#22c55e', marginRight: 12, flexShrink: 0 },
  historyItemCode: { fontSize: 14, fontWeight: '700', color: '#111827', marginBottom: 3 },
  historyItemMeta: { fontSize: 12, color: '#9ca3af' },
  historyBadge: { backgroundColor: '#dcfce7', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4, flexShrink: 0 },
  historyBadgeText: { color: '#16a34a', fontSize: 11, fontWeight: '700' },
  scanScreen: { flex: 1, backgroundColor: '#000', paddingTop: ANDROID_TOP },
  scanTopBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 14, backgroundColor: '#000' },
  backButton: { width: 60 },
  backButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '600' },
  scanScreenTitle: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  cameraWrapper: { width: '100%', height: width, position: 'relative' },
  scanOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: 'center', alignItems: 'center' },
  scanFrame: { width: 220, height: 220, position: 'relative' },
  corner: { position: 'absolute', width: 28, height: 28, borderColor: '#2563eb', borderWidth: 3 },
  cornerTL: { top: 0, left: 0, borderRightWidth: 0, borderBottomWidth: 0, borderTopLeftRadius: 6 },
  cornerTR: { top: 0, right: 0, borderLeftWidth: 0, borderBottomWidth: 0, borderTopRightRadius: 6 },
  cornerBL: { bottom: 0, left: 0, borderRightWidth: 0, borderTopWidth: 0, borderBottomLeftRadius: 6 },
  cornerBR: { bottom: 0, right: 0, borderLeftWidth: 0, borderTopWidth: 0, borderBottomRightRadius: 6 },
  scanBottomPanel: { flex: 1, backgroundColor: '#ffffff', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 24, paddingTop: 22 },
  scanHintBox: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  scanHintText: { fontSize: 14, color: '#64748b', textAlign: 'center', lineHeight: 22 },
  scanResultBox: { backgroundColor: '#f8fafc', borderRadius: 16, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: '#e2e8f0' },
  scanResultLabel: { fontSize: 11, fontWeight: '600', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6 },
  scanResultValue: { fontSize: 16, fontWeight: '700', color: '#0f172a', marginBottom: 4 },
  scanResultType: { fontSize: 12, color: '#64748b' },
  permissionIcon: { fontSize: 52, marginBottom: 16, textAlign: 'center' },
  permissionTitle: { fontSize: 20, fontWeight: '800', color: '#0f172a', marginBottom: 8, textAlign: 'center' },
  permissionSubtitle: { fontSize: 14, color: '#64748b', textAlign: 'center', lineHeight: 22, marginBottom: 24 },
});
